### ISSUE TITLE
Only save the image once in condvert

### ISSUE THREAD

**Issue by stuaxo** [TyperOfCode/image_algorithm#2]
Hi,
   I had a really quick look at your code, condvert saves the image a few times and only once will do.

I wasn't sure if you use python 2 or 3, so used the older print formatting.

```python
def condvert(imggg, pixelo):
    he = pixelo
    img = Image.open(imggg)
    print("resizing from {}/{}".format(img.size))
    w, h = img.size
    wpercent = he / float(h)
    hsize = int(float(w) * float(wpercent))
    img = img.resize((hsize, he), Image.ANTIALIAS)
    print("resized to {}/{}".format(img.size))
    img.save(imggg)
```

I would also consider running the code through something like `black` so it's formatted in a standard way.

Cheers, for the awesome image thingy :)

**Comment by TyperOfCode** [comment]
Thanks!
